[project]
name = "hcmc-realtime-traffic-forecasting-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3",
    "duckdb",
    "ijson",
    "polars",
    "pydantic",
    "pydantic-settings",
    "pytz",
]

[project.scripts]
run-etl = "src.jobs.pipelines.run_etl:main"
check-train-data = "src.jobs.quality.check_train_data:main"
show-train-gaps = "src.jobs.quality.show_train_gaps:main"
prepare-graph = "src.jobs.quality.prepare_graph:main"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["config*", "src*"]
